<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
	<PlatformTarget>x64</PlatformTarget>
	<ApplicationIcon>Assets\LLIcon256x256.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\LedgerLensTransparentDrawing2.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\LLIcon256x256.ico" />
  </ItemGroup>

	<ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LedgerLens.Data\LedgerLens.Data.csproj" />
	  <ProjectReference Include="..\LedgerLens.Services\LedgerLens.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\LedgerLensTransparentDrawing2.png" />
	</ItemGroup>
</Project>
